In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [3]:
### Load the trained model, scaler pickle,onehot
model=load_model('ANNmodel.h5')

with open('label_encoder_gender1.pkl', 'rb') as file:
    label_encoder_gender1 = pickle.load(file)

with open('scaler1.pkl', 'rb') as file:
    scaler1 = pickle.load(file)

In [4]:
# Example input data
input_data = {
    'GENDER': 1,
    'AGE': 50,
    'SMOKING': 1,
    'YELLOW_FINGERS': 1,
    'ANXIETY': 1,
    'PEER_PRESSURE': 1,
    'CHRONIC DISEASE': 2,
    'FATIGUE': 2,
    'ALLERGY': 2,
    'WHEEZING': 2,
    'ALCOHOL CONSUMING': 1,
    'COUGHING':2,
    'SHORTNESS OF BREATH':1,
    'SWALLOWING DIFFICULTY':2,
    'CHEST PAIN':1,
}

In [5]:
input_df=pd.DataFrame([input_data])
input_df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
0,1,50,1,1,1,1,2,2,2,2,1,2,1,2,1


In [6]:
## Encode categorical variables
label_encoder_gender1.fit(input_df['GENDER'])
input_df['GENDER'] = label_encoder_gender1.transform(input_df['GENDER'])

In [7]:
from sklearn.preprocessing import StandardScaler

# Fit scaler on training data
scaler1 = StandardScaler()
scaler1.fit(input_df)

# Transform input data (e.g., test data or new input)
input_scaled1 = scaler1.transform(input_df)
print(input_scaled1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
## Scaling the input data
input_scaled1=scaler1.transform(input_df)
input_scaled1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
## PRedict churn
prediction=model.predict(input_scaled1)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[0.91029716]], dtype=float32)

In [10]:
prediction_proba = prediction[0][0]

In [11]:
if prediction_proba > 0.5:
    print('The patient is diagnosed with lung cancer.')
else:
    print('The patient is not diagnosed with lung cancer.')

The patient is diagnosed with lung cancer.
